### ISSUE TITLE
Informative and interesting -- a couple of suggestions and a reference

### ISSUE THREAD

**Issue by PaoloMissier** [alex-ball/HowTo-DataImpact#2]
Interesting and topical guide. My personal interest is in models for ascribing credit to data owners through multiple generations of data reuse and derivation. I am convinced that partial but fair credit to original owners, if done right, can go a long way towards providing the necessary motivations (the 'carrot' side of the equation) especially to career-focused researchers.
I think this article stops short of tackling the specific issue of credit models -- possibly because there are few proposals written down on how to go about this, but anything that goes beyond "download count" is a welcome step in the right direction. So, one more recent reference you may find interesting on this specific direction of research  (I have been otherwise impressed with your bibliography)

> Katz, Daniel S. “Transitive Credit as a Means to Address Social and Technological Concerns Stemming from Citation and Attribution of Digital Products.” Journal of Open Research Software 2, no. 1 (2014): e20.
> http://openresearchsoftware.metajnl.com/article/view/jors.be

**Disconnect data citation from paper citation**
I am also convinced that the culture of data citation should be allowed to evolve independently from that of paper citation. Currently, data is cited mainly from within papers. I argue that if you encapsulate data publications as metadata-rich Research Objects (http://www.researchobject.org/), then you already have a great mechanism in place to build a graph of data citations that is completely independent from, but linkable to if needed, that of paper citation. I think this decoupling will be beneficial as it makes it easier to cite data sources when you publish your derived data product -- as opposed to when you publish your next paper. The link between the two can still be done later, of course.

A couple of quick specific comments:

**[ke2013vrd]** which publication is this?? can't find it in your footnotes or biblio (ironically!)

**Regarding the REF 2014 impact**: the definition of impact in the REF context is very strict and clearly distinct, I think, from what is meant here. In particular, it's not about academic impact, but rather societal and business impact. As such, it must be backed up by very solid evidence which is not, I'm afraid, of the form discussed in this paper (ie, data reuse).

Paolo Missier
Newcastle University, School of Computing Science

**Comment by alex-ball** [comment]
We will respond to the rest of your comments soon, but on the very specific issue of `[@ke2013vrd]` you can find it on lines 210-219 of `impact.bib`, and it refers to the 2013 Knowledge Exchange report, ‘[The Value of Research Data](http://www.knowledge-exchange.info/datametrics)’.

**Comment by MonicaDuke** [comment]
Thank you very much for taking the time to engage with this document and to send us further information.  We did consider originally the issue of contributor roles, however we decided that this would be more appropriate in a document about attribution and credit, rather than data impact.  We will be updating the guide on data citation shortly, and the reference from Katz may fit better there. 
We have now included a reference to research objects, since being able to follow the data citation network across data objects would be part of the picture of tracing data impact, if it became widely implemented.
Finally, we wanted to clarify that the guide is more generally about tracking the impact of data, rather than simply data re-use, which would be more narrow.  In other words if a released data set led to a change in direction of policy or sparked discussions, that would be valid impact for that data, irrespective of whether the data was "re-used" (re-analysed, used to produce derivative data etc).
